import './Draw.scss';

function Draw() {

  const color1 = "#00B9FF";
const color2 = "#00FF78";
const color3 = "#1F1F1F";
const color5 = "grey";
const color6 = "white";
  return (
    // <Anim className="draw animation1" iv="iv1">
    <div className="draw">
        <svg
          viewBox="0 0 900 273"
          xmlns="http://www.w3.org/2000/svg"
          version="1.1"
          enableBackground="new 0 0 100 100"
          xmlSpace="preserve"
        >
          <defs>
            <g id="computer">
              <rect
                id="computer_outer"
                x="225"
                y="10"
                rx="8"
                ry="12"
                width="300"
                height="220"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill={color6}
              />
              <rect
                id="computer_screen"
                x="240"
                y="25"
                rx="4"
                ry="6"
                width="270"
                height="170"
                fill={color1}
              />
              <circle
                id="computerBtn"
                cx="375"
                cy="210"
                r="5"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill="green"
              />
              <line
                x1="350"
                x2="350"
                y1="230"
                y2="260"
                stroke="#1F1F1F"
                strokeWidth="3px"
              />
              <line
                x1="400"
                x2="400"
                y1="230"
                y2="260"
                stroke="#1F1F1F"
                strokeWidth="3px"
              />
              <rect
                x="320"
                y="260"
                rx="2"
                ry="6"
                width="110"
                height="12"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill="white"
              />
            </g>

            <g id="logoAnime1">
              <circle
                id="la1c1"
                className="la1c"
                cx="375"
                cy="110"
                r="50"
                fill="none"
                stroke="white"
                strokeWidth="5px"
                strokeDasharray="14"
                strokeLinecap="round"
              />
              <circle
                id="la1c2"
                className="la1c"
                cx="375"
                cy="110"
                r="40"
                fill="none"
                stroke="white"
                strokeWidth="2px"
                strokeDasharray="14"
              />
              <line
                id="la1l1"
                className="la1l"
                x1="355"
                x2="355"
                y1="100"
                y2="120"
                stroke="white"
                strokeWidth="4px"
              >
                <animateTransform
                  id="test"
                  attributeName="transform"
                  attributeType="XML"
                  type="translate"
                  dur="2s"
                  values="0 10; 0 -10; 0 10"
                  repeatCount="indefinite"
                  begin="0s"
                />
              </line>
              <line
                id="la1l2"
                className="la1l"
                x1="365"
                x2="365"
                y1="100"
                y2="120"
                stroke="white"
                strokeWidth="4px"
              >
                <animateTransform
                  attributeName="transform"
                  attributeType="XML"
                  type="translate"
                  dur="2s"
                  values="0 10; 0 -10; 0 10"
                  repeatCount="indefinite"
                  begin="0.2s"
                />
              </line>
              <line
                id="la1l3"
                className="la1l"
                x1="375"
                x2="375"
                y1="100"
                y2="120"
                stroke="white"
                strokeWidth="4px"
              >
                <animateTransform
                  attributeName="transform"
                  attributeType="XML"
                  type="translate"
                  dur="2s"
                  values="0 10; 0 -10; 0 10"
                  repeatCount="indefinite"
                  begin="0.4s"
                />
              </line>
              <line
                id="la1l4"
                className="la1l"
                x1="385"
                x2="385"
                y1="100"
                y2="120"
                stroke="white"
                strokeWidth="4px"
              >
                <animateTransform
                  attributeName="transform"
                  attributeType="XML"
                  type="translate"
                  dur="2s"
                  values="0 10; 0 -10; 0 10"
                  repeatCount="indefinite"
                  begin="0.6s"
                />
              </line>
              <line
                id="la1l5"
                x1="395"
                x2="395"
                y1="100"
                y2="120"
                stroke="white"
                strokeWidth="4px"
              >
                <animateTransform
                  attributeName="transform"
                  attributeType="XML"
                  type="translate"
                  dur="2s"
                  values="0 10; 0 -10; 0 10"
                  repeatCount="indefinite"
                  begin="0.8s"
                />
              </line>
            </g>

            <g id="computer2">
              <rect
                x="470"
                y="110"
                rx="8"
                ry="10"
                width="210"
                height="150"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill="white"
              />
              <rect
                x="450"
                y="250"
                rx="8"
                ry="10"
                width="250"
                height="22"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill="white"
              />
              <rect
                id="computer2_screen"
                x="480"
                y="125"
                rx="3"
                ry="6"
                width="190"
                height="110"
                fill={color2}
              />
              <rect
                x="555"
                y="250"
                rx="3"
                ry="6"
                width="40"
                height="6"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill="white"
              />
            </g>

            <g id="mobile">
              <rect
                x="180"
                y="150"
                rx="8"
                ry="10"
                width="60"
                height="122"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill="white"
              />
              <line
                x1="190"
                x2="230"
                y1="155"
                y2="155"
                stroke="#717171"
                strokeWidth="3px"
                strokeLinecap="round"
              />
              <rect
                id="mobile_screen"
                x="180"
                y="160"
                rx="0"
                ry="0"
                width="60"
                height="95"
                stroke="#1F1F1F"
                strokeWidth="2px"
                fill={color3}
              />
              <circle
                cx="210"
                cy="263"
                r="3"
                stroke="#1F1F1F"
                strokeWidth="2px"
                fill="#1F1F1F"
              />
              <circle
                id="_button"
                cx="195"
                cy="165"
                r="0.1"
                strokeWidth="2px"
                fill={color1}
              />
              <line
                id="phoneL1"
                x1="208"
                x2="208"
                y1="198"
                y2="198"
                stroke="white"
                strokeWidth="3px"
                strokeLinecap="round"
              />
              <line
                id="phoneL2"
                x1="208"
                x2="208"
                y1="205"
                y2="205"
                stroke="white"
                strokeWidth="3px"
                strokeLinecap="round"
              />
              <line
                id="phoneL3"
                x1="208"
                x2="208"
                y1="212"
                y2="212"
                stroke="white"
                strokeWidth="3px"
                strokeLinecap="round"
              />
            </g>

            <g id="mouse">
              <circle
                cx="730"
                cy="277"
                r="20"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill="white"
              />
              <line
                x1="710"
                x2="750"
                y1="272"
                y2="272"
                stroke="#1F1F1F"
                strokeWidth="3px"
              />
              <line
                x1="730"
                x2="730"
                y1="265"
                y2="257"
                stroke="#1F1F1F"
                strokeWidth="3px"
                strokeLinecap="round"
              />
            </g>

            <g id="cup">
              <circle
                cx="864"
                cy="239"
                r="18"
                stroke="white"
                strokeWidth="8px"
                fill="transparent"
              />
              <circle
                cx="864"
                cy="239"
                r="23"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill="transparent"
              />

              <circle
                cx="864"
                cy="239"
                r="15"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill="transparent"
              />
              <rect
                id="cup_tea"
                x="800"
                y="202"
                rx="8"
                ry="10"
                width="63"
                height="70"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill={color5}
              />
              <rect
                id="QuantityThe"
                x="800"
                y="202"
                rx="0"
                ry="0"
                width="63"
                height="12"
                fill="white"
              />
              <rect
                x="800"
                y="202"
                rx="8"
                ry="10"
                width="63"
                height="70"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill="rgba(31,31,31,0.2)"
              />
              <path
                id="ficelleThe"
                d="M820 202 C 835 160, 840 220, 840 230"
                stroke="#1F1F1F"
                fill="transparent"
                strokeWidth="3px"
              />
              <rect
                id="cup_bag"
                x="830"
                y="222"
                rx="4"
                ry="4"
                width="20"
                height="20"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill={color2}
              />
            </g>

            <g id="cup_smoke">
              <circle
                className="tasseFume"
                cx="810"
                cy="215"
                r="0.1"
                fill="#B4B4B4"
              >
                <animate
                  className="anime1"
                  attributeName="cy"
                  begin="0.66s"
                  values="215;175;155"
                  dur="2s"
                  fill="freeze"
                  repeatCount="indefinite"
                />
                <animate
                  className="anime1"
                  attributeName="r"
                  begin="0.66s"
                  values="0.1;8;16"
                  dur="2s"
                  fill="freeze"
                  repeatCount="indefinite"
                />
                <animate
                  className="anime1"
                  attributeName="fill"
                  begin="0.66s"
                  values="#B4B4B4;transparent"
                  dur="2s"
                  fill="freeze"
                  repeatCount="indefinite"
                />
              </circle>
              <circle
                className="tasseFume"
                cx="830"
                cy="215"
                r="0.1"
                fill="#B4B4B4"
              >
                <animate
                  className="anime2"
                  attributeName="cy"
                  values="215;175;155"
                  dur="2s"
                  repeatCount="indefinite"
                />
                <animate
                  className="anime2"
                  attributeName="r"
                  values="0.1;8;16"
                  dur="2s"
                  repeatCount="indefinite"
                />
                <animate
                  className="anime2"
                  attributeName="fill"
                  values="#B4B4B4;transparent"
                  dur="2s"
                  repeatCount="indefinite"
                />
              </circle>
              <circle
                className="tasseFume"
                cx="850"
                cy="215"
                r="0.1"
                fill="#B4B4B4"
              >
                <animate
                  className="anime3"
                  attributeName="cy"
                  begin="1.33s"
                  values="215;175;155"
                  dur="2s"
                  repeatCount="indefinite"
                />
                <animate
                  className="anime3"
                  attributeName="r"
                  begin="1.33s"
                  values="0.1;8;16"
                  dur="2s"
                  repeatCount="indefinite"
                />
                <animate
                  className="anime3"
                  attributeName="fill"
                  begin="1.33s"
                  values="#B4B4B4;transparent"
                  dur="2s"
                  repeatCount="indefinite"
                />
              </circle>
            </g>

            <g id="popup1">
              <rect
                id="popup1_back"
                x="130"
                y="35"
                rx="8"
                ry="10"
                width="180"
                height="100"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill={color3}
              />
              <rect
                x="130"
                y="35"
                rx="4"
                ry="4"
                width="180"
                height="16"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill="white"
              />
              <circle
                id="popup1_btn1"
                cx="145"
                cy="42"
                r="2"
                strokeWidth="2px"
                stroke={color3}
                fill={color3}
              />
              <circle
                id="popup1_btn2"
                cx="158"
                cy="42"
                r="2"
                strokeWidth="2px"
                stroke={color2}
                fill={color2}
              />
              <circle
                id="popup1_btn3"
                cx="171"
                cy="42"
                r="2"
                strokeWidth="2px"
                stroke={color1}
                fill={color1}
              />
              <line
                x1="145"
                x2="155"
                y1="60"
                y2="60"
                stroke="#373737"
                strokeWidth="3px"
                strokeLinecap="round"
              />
              <line
                x1="145"
                x2="155"
                y1="70"
                y2="70"
                stroke="#373737"
                strokeWidth="3px"
                strokeLinecap="round"
              />
              <line
                x1="145"
                x2="155"
                y1="80"
                y2="80"
                stroke="#373737"
                strokeWidth="3px"
                strokeLinecap="round"
              />

              <line
                id="popup1_line1"
                x1="160"
                x2="180"
                y1="60"
                y2="60"
                strokeWidth="3px"
                strokeLinecap="round"
                stroke={color1}
              />
              <line
                id="popup1_line2"
                x1="160"
                x2="175"
                y1="70"
                y2="70"
                strokeWidth="3px"
                strokeLinecap="round"
                stroke={color2}
              />
              <line
                id="popup1_line3"
                x1="160"
                x2="190"
                y1="80"
                y2="80"
                stroke={color1}
                strokeWidth="3px"
                strokeLinecap="round"
              />

              <line
                id="popup1_line4"
                x1="185"
                x2="200"
                y1="60"
                y2="60"
                stroke={color2}
                strokeWidth="3px"
                strokeLinecap="round"
              />
              <line
                id="popup1_line5"
                x1="180"
                x2="210"
                y1="70"
                y2="70"
                stroke={color1}
                strokeWidth="3px"
                strokeLinecap="round"
              />
              <line
                id="popup1_line6"
                x1="195"
                x2="205"
                y1="80"
                y2="80"
                stroke={color2}
                strokeWidth="3px"
                strokeLinecap="round"
              />

              <line
                id="popup1_line7"
                x1="205"
                x2="220"
                y1="60"
                y2="60"
                stroke={color1}
                strokeWidth="3px"
                strokeLinecap="round"
              />
              <line
                id="popup1_line8"
                x1="215"
                x2="230"
                y1="70"
                y2="70"
                stroke={color2}
                strokeWidth="3px"
                strokeLinecap="round"
              />
              <line
                id="popup1_line9"
                x1="210"
                x2="240"
                y1="80"
                y2="80"
                stroke={color1}
                strokeWidth="3px"
                strokeLinecap="round"
              />
            </g>

            <g id="popup2">
              <rect
                x="620"
                y="50"
                rx="4"
                ry="4"
                width="150"
                height="110"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill="white"
              />
              <rect
                id="popup2_bar"
                x="620"
                y="50"
                rx="4"
                ry="4"
                width="150"
                height="16"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill={color3}
              />
              <circle
                id="popup2_btn1"
                cx="635"
                cy="58"
                r="2"
                strokeWidth="2px"
                stroke={color6}
                fill={color6}
              />
              <circle
                id="popup2_btn2"
                cx="648"
                cy="58"
                r="2"
                strokeWidth="2px"
                stroke={color2}
                fill={color2}
              />
              <circle
                id="popup2_btn3"
                cx="661"
                cy="58"
                r="2"
                strokeWidth="2px"
                stroke={color1}
                fill={color1}
              />
              <rect
                id="popup2_graph1"
                x="640"
                y="100"
                rx="1"
                ry="1"
                width="10"
                height="40"
                strokeWidth="3px"
                stroke={color2}
                fill={color2}
              />
              <rect
                id="popup2_graph2"
                x="660"
                y="85"
                rx="1"
                ry="1"
                width="10"
                height="55"
                strokeWidth="3px"
                stroke={color1}
                fill={color1}
              />
              <rect
                id="popup2_graph3"
                x="680"
                y="92"
                rx="1"
                ry="1"
                width="10"
                height="48"
                strokeWidth="3px"
                stroke={color3}
                fill={color3}
              />
              <line
                x1="715"
                x2="740"
                y1="90"
                y2="90"
                stroke="#1F1F1F"
                strokeWidth="6px"
                strokeLinecap="round"
              />
              <line
                x1="715"
                x2="740"
                y1="110"
                y2="110"
                stroke="#1F1F1F"
                strokeWidth="6px"
                strokeLinecap="round"
              />
              <line
                x1="715"
                x2="740"
                y1="130"
                y2="130"
                stroke="#1F1F1F"
                strokeWidth="6px"
                strokeLinecap="round"
              />
            </g>

            <g id="book">
              <path
                id="book_cover1"
                d="M50 222 C 20 222, 20 272, 50 272"
                stroke="#1F1F1F"
                fill={color1}
                strokeWidth="3px"
                strokeLinecap="round"
              />
              <path
                d="M50 232 C 35 232, 35 262, 50 262 L130 262 C 110 261, 110 232, 130 232 L50 232"
                stroke="#1F1F1F"
                fill="white"
                strokeWidth="3px"
                strokeLinecap="round"
              />
              <rect
                id="book_cover2"
                x="50"
                y="222"
                rx="0"
                ry="0"
                width="80"
                height="10"
                strokeWidth="0px"
                fill={color1}
              />
              <rect
                id="book_cover3"
                x="50"
                y="262"
                rx="0"
                ry="0"
                width="80"
                height="10"
                strokeWidth="0px"
                fill={color1}
              />
              <line
                x1="50"
                x2="130"
                y1="222"
                y2="222"
                stroke="#1F1F1F"
                strokeWidth="3px"
                strokeLinecap="round"
                fill="00B9FF"
              />
              <line
                x1="50"
                x2="130"
                y1="232"
                y2="232"
                stroke="#1F1F1F"
                strokeWidth="3px"
                strokeLinecap="round"
                fill="00B9FF"
              />
              <line
                x1="50"
                x2="130"
                y1="262"
                y2="262"
                stroke="#1F1F1F"
                strokeWidth="3px"
                strokeLinecap="round"
                fill="00B9FF"
              />
              <line
                x1="50"
                x2="130"
                y1="272"
                y2="272"
                stroke="#1F1F1F"
                strokeWidth="3px"
                strokeLinecap="round"
                fill="00B9FF"
              />
              <line
                x1="130"
                x2="130"
                y1="223"
                y2="230"
                stroke="#1F1F1F"
                strokeWidth="3px"
                strokeLinecap="round"
                fill="00B9FF"
              />
              <line
                x1="130"
                x2="130"
                y1="263"
                y2="270"
                stroke="#1F1F1F"
                strokeWidth="3px"
                strokeLinecap="round"
                fill="00B9FF"
              />
              <line
                x1="55"
                x2="115"
                y1="240"
                y2="240"
                stroke="#1F1F1F"
                strokeWidth="3px"
                strokeLinecap="round"
                fill="00B9FF"
              />
              <line
                x1="55"
                x2="115"
                y1="252"
                y2="252"
                stroke="#1F1F1F"
                strokeWidth="3px"
                strokeLinecap="round"
                fill="00B9FF"
              />
            </g>

            <g id="popup3">
              <circle
                id="popup3_outer"
                cx="130"
                cy="140"
                r="40"
                stroke={color3}
                fill="none"
                strokeWidth="5px"
              >
                <animate
                  attributeType="CSS"
                  attributeName="opacity"
                  values="1;0"
                  dur="2s"
                  repeatCount="indefinite"
                />
                <animate
                  attributeName="stroke-width"
                  values="10;30;40"
                  dur="2s"
                  repeatCount="indefinite"
                />
              </circle>
              <circle
                id="popup3_pulse"
                cx="130"
                cy="140"
                r="40"
                stroke={color3}
                fill="none"
                strokeWidth="5px"
              >
                <animate
                  attributeType="CSS"
                  attributeName="opacity"
                  values="1;0"
                  dur="2s"
                  repeatCount="indefinite"
                  begin="1s"
                />
                <animate
                  attributeName="stroke-width"
                  values="10;30;40"
                  dur="2s"
                  repeatCount="indefinite"
                  begin="1s"
                />
              </circle>
              <circle
                id="popup3_background"
                cx="130"
                cy="140"
                r="45"
                stroke="#1F1F1F"
                strokeWidth="3px"
                fill={color2}
              />
              <polyline
                points="155 125 140 140 155 155"
                stroke="#1F1F1F"
                strokeWidth="3px"
                strokeLinecap="round"
                fill="none"
                strokeLinejoin="miter"
              />
              <line
                id="popup3L"
                x1="122"
                x2="137"
                y1="160"
                y2="120"
                stroke="#1F1F1F"
                strokeWidth="3px"
                strokeLinecap="round"
              />
              <polyline
                points="105 125 120 140 105 155"
                stroke="#1F1F1F"
                strokeWidth="3px"
                strokeLinecap="round"
                fill="none"
                strokeLinejoin="miter"
              />
            </g>

            <g id="logoAnime3" />
          </defs>
          <use href="#computer" />
          <use href="#logoAnime1" />
          <use href="#computer2" />
          <use href="#logoAnime2" />
          <use href="#mobile" />
          <use href="#mouse" />
          <use href="#cup" />
          <use href="#cup_smoke" />
          <use href="#book" />
          <use href="#popup1" />
          <use href="#popup2" />
          <use href="#logoAnime3" />
          <use href="#popup3" />
          <use href="#symbol" />
        </svg>
        </div>
    // </Anim>
  );
}

export default Draw;
